{{- if .Values.sync.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "apicurio-registry.fullname" . }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      # the Java operator SDK seems to need listing CRDs
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - artifact.apicur.io
    resources:
      # operator main custom resources
      - artifacts
      - artifacts/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "apicurio-registry.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "apicurio-registry.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "apicurio-registry.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
