{{- if or .Values.registry.enabled .Values.sync.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apicurio-registry.name" . }}
  labels:
    {{- include "apicurio-registry.labels" . | nindent 4 }}
{{- end }}
