{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apicurio-registry.serviceAccountName" . }}
  labels:
    {{- include "apicurio-registry.labels" . | nindent 4 }}
{{- end }}
