{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "apicurio-registry.labels" . | nindent 4 }}
  name: {{ include "apicurio-registry.fullname" . }}
spec:
  selector:
    {{- include "apicurio-registry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: registry
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: {{ .Values.registry.service.type }}
{{- end }}
